name: Update Gradle Wrapper

permissions:
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
